### ISSUE TITLE
Thank you and for your efforts 

### ISSUE THREAD

**Issue by b12b12** [Wikidepia/hektCaptcha-extension#38] opened 2023-05-08 21:09 UTC
I have a problem I have to switch my browser to english for it to work recaptch and hcaptcha 
I hope to solve this problem

**Comment by Serega007RU** [comment] 2023-05-08 21:36
It looks like it's a duplicate of #36

**Comment by Pocker88** [comment] 2023-05-09 03:47
😅

**Comment by alvaradolisandro** [comment] 2023-05-09 13:25
https://accounts.hcaptcha.com/demo?sitekey=195eeb9f-8f50-4a9c-abfc-a78ceaa3cdde   
this challenge is not solved by the extension

**Comment by alvaradolisandro** [comment] 2023-05-09 22:34
https://accounts.hcaptcha.com/demo?sitekey=195eeb9f-8f50-4a9c-abfc-a78ceaa3cdde
this challenge is not solved by the extension

**Comment by Wikidepia** [comment] 2023-05-09 22:36
Hi, please do not spam. I can read it already :)

**Comment by Wikidepia** [comment] 2023-05-09 22:36
Closed, duplicate #36

**Closed by Wikidepia** 2023-05-09 22:36 UTC
